name: "headless_display"
description: "Creates a virtual display so e.g Firefox can start"

runs:
  using: "composite"
  steps:
    - name: Install Xvfb on Linux and macOS
      if: runner.os != 'Windows'
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get install -y xvfb
          which Xvfb
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install --cask xquartz
          echo "XQUARTZ installed"
          sudo /opt/X11/libexec/privileged_startx || true
          sleep 5  # Wait for XQuartz to fully start
          echo "/opt/X11/bin" >> $GITHUB_PATH
        else
          echo "This Action is only applicable for Linux and macOS. The current runner is $RUNNER_OS, so this does nothing."
          exit 0
        fi
      shell: bash
    - name: Set DISPLAY env variable
      if: runner.os != 'Windows'
      run: echo "DISPLAY=:99.0" >> $GITHUB_ENV
      shell: bash
    - name: Create virtual display with Xvfb
      if: runner.os != 'Windows'
      run: |
        Xvfb :99 -screen 0 1024x768x32 > /dev/null 2>&1 &
        # Wait for Xvfb to start
        sleep 3
      shell: bash
